CREATE DATABASE IF NOT EXISTS Jobay;
USE Jobay;
CREATE TABLE IF NOT EXISTS Timeblock (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    start_time FLOAT UNSIGNED NOT NULL,
    end_time FLOAT UNSIGNED NOT NULL
);
CREATE TABLE IF NOT EXISTS User (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    image INT UNSIGNED UNIQUE KEY NOT NULL,
    first_name VARCHAR(32) NOT NULL,
    last_name VARCHAR(16) NOT NULL,
    location INT UNSIGNED NOT NULL,
    completed_jobs INT UNSIGNED NOT NULL,
    rating FLOAT UNSINGED NOT NULL,
    cnt_ratings SMALLINT UNSIGNED NOT NULL,
    description VARCHAR(1024) NOT NULL
);
CREATE TABLE IF NOT EXISTS ReadyTimeblock (
    id_user INT UNSIGNED NOT NULL,
    id_timeblock INT UNSIGNED NOT NULL,
    FOREIGN KEY (id_user) REFERENCES User(id),
    FOREIGN KEY (id_timeblock) REFERENCES Timeblocks(id)
);
CREATE TABLE IF NOT EXISTS Message (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_send INT UNSIGNED NOT NULL,
    user_receive INT UNSIGNED NOT NULL,
    content VARCHAR(512) NOT NULL,
    time float UNSIGNED NOT NULL,
    FOREIGN KEY(user_send) REFERENCES User(id),
    FOREIGN KEY(user_receive) REFERENCES User(id)
);
CREATE TABLE IF NOT EXISTS Tag (
    id TINYINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS UserTag (
    id_user INT UNSIGNED NOT NULL,
    id_tag TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY(id_user) REFERENCES User(id),
    FOREIGN KEY(id_tag) REFERENCES Tag(id)
);
CREATE TABLE IF NOT EXISTS Status (
    id TINYINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS Job (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    image UNIQUE KEY NOT NULL,
    status TINYINT UNSIGNED NOT NULL,
    name VARCHAR(32) NOT NULL,
    duration SMALLINT UNSIGNED NOT NULL,
    time_start FLOAT UNSINGED NOT NULL,
    payment FLOAT UNSIGNED NOT NULL,
    employer INT UNSIGNED NOT NULL,
    FOREIGN KEY (status) REFERENCES Status(id),
    FOREIGN KEY (employer) REFERENCES User(id)
);
CREATE TABLE IF NOT EXISTS JobTab (
    id_job INT UNSIGNED NOT NULL,
    id_tag TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (id_job) REFERENCES Job(id),
    FOREIGN KEY (id_tag) REFERENCES Tag(id)
);
CREATE TABLE IF NOT EXISTS City (
    id INT UNSIGNED PRIMARY KEY NOT NULL,
    name VARCHAR(32) NOT NULL
);
CREATE TABLE IF NOT EXISTS Location (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    post_code SMALLINT UNSIGNED NOT NULL,
    city INT UNSIGNED NOT NULL
);